POST http://localhost:7070/api/travelhelper/findroute
Content-type: application/json


{
    "startStation": "Bagsværd St.",
    "endStation": "Høje Taastrup St."


}
###
GET http://localhost:7070/api/travelhelper/getallstationsforyourroute
###

POST http://localhost:7070/api/travelhelper/findprice
Content-type: application/json


{
  "startStation": "Bagsværd St.",
  "endStation": "Høje Taastrup St."


}
###

GET http://localhost:7070/api/travelhelper/price

###

POST http://localhost:7070/api/travelhelper/user/register
Content-type: application/json

{
  "username": "test",
  "password": "test"
}

> {% client.global.set("token", response.body.token); %}

###

POST http://localhost:7070/api/travelhelper/user/login
Content-type: application/json

{
  "username": "test",
  "password": "test"
}